site_name: E-lunta

docs_dir: ./docs
site_dir: ../docs

repo_url: https://github.com/danielmartling/lunta

nav:
  # - Home: index.md
  # - About: about.md
  - Platser:
    - Lägerbålsplatser och vindskydd: lbp.md
    - Inomhus: inomhus.md
    - Utomhus: utomhus.md
theme:
  name: material
  logo: ./img/Scoutsymbolen_white.png
  language: sv

markdown_extensions:
  - toc:
      baselevel: 1
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - glightbox
  - search

  